development:
  adapter:  postgresql
  encoding: unicode
  database: sf_movies_development
  pool:     25
  username: renangurgel

test:
  adapter:  postgresql
  encoding: unicode
  database: sf_movies_test
  pool:     5
  username: renangurgel